// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZanganosSA.Data;

#nullable disable

namespace ZanganosSA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525234058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZanganosSA.Models.Apiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeccionalPolicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionGps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("ZanganosSA.Models.Barril", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CosechaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvasado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PesoNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CosechaId");

                    b.ToTable("Barriles");
                });

            modelBuilder.Entity("ZanganosSA.Models.Colmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoGeneral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoReina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaInspeccion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Colmenas");
                });

            modelBuilder.Entity("ZanganosSA.Models.ColmenaCosecha", b =>
                {
                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<int>("CosechaId")
                        .HasColumnType("int");

                    b.HasKey("ColmenaId", "CosechaId");

                    b.HasIndex("CosechaId");

                    b.ToTable("ColmenaCosechas");
                });

            modelBuilder.Entity("ZanganosSA.Models.Cosecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCosecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PesoTotalEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Cosechas");
                });

            modelBuilder.Entity("ZanganosSA.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ZanganosSA.Models.Barril", b =>
                {
                    b.HasOne("ZanganosSA.Models.Cosecha", "Cosecha")
                        .WithMany("Barriles")
                        .HasForeignKey("CosechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ZanganosSA.Models.Colmena", b =>
                {
                    b.HasOne("ZanganosSA.Models.Apiario", "Apiario")
                        .WithMany("Colmenas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("ZanganosSA.Models.ColmenaCosecha", b =>
                {
                    b.HasOne("ZanganosSA.Models.Colmena", "Colmena")
                        .WithMany("ColmenaCosechas")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZanganosSA.Models.Cosecha", "Cosecha")
                        .WithMany("ColmenaCosechas")
                        .HasForeignKey("CosechaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colmena");

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ZanganosSA.Models.Cosecha", b =>
                {
                    b.HasOne("ZanganosSA.Models.Apiario", "Apiario")
                        .WithMany("Cosechas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("ZanganosSA.Models.Tratamiento", b =>
                {
                    b.HasOne("ZanganosSA.Models.Colmena", "Colmena")
                        .WithMany("Tratamientos")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("ZanganosSA.Models.Apiario", b =>
                {
                    b.Navigation("Colmenas");

                    b.Navigation("Cosechas");
                });

            modelBuilder.Entity("ZanganosSA.Models.Colmena", b =>
                {
                    b.Navigation("ColmenaCosechas");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("ZanganosSA.Models.Cosecha", b =>
                {
                    b.Navigation("Barriles");

                    b.Navigation("ColmenaCosechas");
                });
#pragma warning restore 612, 618
        }
    }
}
